// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_keys.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (user_id, name, key_hash, key_prefix)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, name, key_hash, key_prefix, created_at, last_used_at, is_active
`

type CreateAPIKeyParams struct {
	UserID    int32  `json:"user_id"`
	Name      string `json:"name"`
	KeyHash   string `json:"key_hash"`
	KeyPrefix string `json:"key_prefix"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.UserID,
		arg.Name,
		arg.KeyHash,
		arg.KeyPrefix,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.IsActive,
	)
	return i, err
}

const deleteAPIKey = `-- name: DeleteAPIKey :exec
UPDATE api_keys SET is_active = false WHERE id = $1
`

func (q *Queries) DeleteAPIKey(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAPIKey, id)
	return err
}

const getAPIKeyByID = `-- name: GetAPIKeyByID :one
SELECT id, user_id, name, key_hash, key_prefix, created_at, last_used_at, is_active FROM api_keys WHERE id = $1
`

func (q *Queries) GetAPIKeyByID(ctx context.Context, id pgtype.UUID) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByID, id)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.IsActive,
	)
	return i, err
}

const getAPIKeyByPrefix = `-- name: GetAPIKeyByPrefix :one
SELECT id, user_id, name, key_hash, key_prefix, created_at, last_used_at, is_active FROM api_keys 
WHERE key_prefix = $1 AND is_active = true 
LIMIT 1
`

func (q *Queries) GetAPIKeyByPrefix(ctx context.Context, keyPrefix string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByPrefix, keyPrefix)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.IsActive,
	)
	return i, err
}

const getAPIKeyUsageLogs = `-- name: GetAPIKeyUsageLogs :many
SELECT id, api_key_id, endpoint, method, ip_address, created_at FROM api_key_logs 
WHERE api_key_id = $1 
ORDER BY created_at DESC 
LIMIT $2 OFFSET $3
`

type GetAPIKeyUsageLogsParams struct {
	ApiKeyID pgtype.UUID `json:"api_key_id"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

func (q *Queries) GetAPIKeyUsageLogs(ctx context.Context, arg GetAPIKeyUsageLogsParams) ([]ApiKeyLog, error) {
	rows, err := q.db.Query(ctx, getAPIKeyUsageLogs, arg.ApiKeyID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiKeyLog
	for rows.Next() {
		var i ApiKeyLog
		if err := rows.Scan(
			&i.ID,
			&i.ApiKeyID,
			&i.Endpoint,
			&i.Method,
			&i.IpAddress,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAPIKeysByUserID = `-- name: GetAPIKeysByUserID :many
SELECT id, user_id, name, key_hash, key_prefix, created_at, last_used_at, is_active FROM api_keys 
WHERE user_id = $1 AND is_active = true 
ORDER BY created_at DESC LIMIT 5
`

func (q *Queries) GetAPIKeysByUserID(ctx context.Context, userID int32) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, getAPIKeysByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiKey
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.KeyHash,
			&i.KeyPrefix,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const logAPIKeyUsage = `-- name: LogAPIKeyUsage :exec
INSERT INTO api_key_logs (api_key_id, endpoint, method, ip_address)
VALUES ($1, $2, $3, $4)
`

type LogAPIKeyUsageParams struct {
	ApiKeyID  pgtype.UUID `json:"api_key_id"`
	Endpoint  string      `json:"endpoint"`
	Method    pgtype.Text `json:"method"`
	IpAddress pgtype.Text `json:"ip_address"`
}

func (q *Queries) LogAPIKeyUsage(ctx context.Context, arg LogAPIKeyUsageParams) error {
	_, err := q.db.Exec(ctx, logAPIKeyUsage,
		arg.ApiKeyID,
		arg.Endpoint,
		arg.Method,
		arg.IpAddress,
	)
	return err
}

const updateAPIKeyLastUsed = `-- name: UpdateAPIKeyLastUsed :exec
UPDATE api_keys SET last_used_at = NOW() WHERE id = $1
`

func (q *Queries) UpdateAPIKeyLastUsed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateAPIKeyLastUsed, id)
	return err
}
