// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: broadcast.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBroadcastJob = `-- name: CreateBroadcastJob :one
INSERT INTO broadcast_jobs (user_id, device_id, name, message_type, content, media_url, media_filename, cooldown, is_scheduled, scheduled_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, COALESCE($9::boolean, FALSE), $10::timestamptz)
RETURNING id, user_id, device_id, name, message_type, content, media_url, media_filename, cooldown, status, is_scheduled, scheduled_at, created_at, updated_at
`

type CreateBroadcastJobParams struct {
	UserID        pgtype.Int4        `json:"user_id"`
	DeviceID      pgtype.Text        `json:"device_id"`
	Name          string             `json:"name"`
	MessageType   pgtype.Text        `json:"message_type"`
	Content       string             `json:"content"`
	MediaUrl      pgtype.Text        `json:"media_url"`
	MediaFilename pgtype.Text        `json:"media_filename"`
	Cooldown      pgtype.Int4        `json:"cooldown"`
	IsScheduled   pgtype.Bool        `json:"is_scheduled"`
	ScheduledAt   pgtype.Timestamptz `json:"scheduled_at"`
}

func (q *Queries) CreateBroadcastJob(ctx context.Context, arg CreateBroadcastJobParams) (BroadcastJob, error) {
	row := q.db.QueryRow(ctx, createBroadcastJob,
		arg.UserID,
		arg.DeviceID,
		arg.Name,
		arg.MessageType,
		arg.Content,
		arg.MediaUrl,
		arg.MediaFilename,
		arg.Cooldown,
		arg.IsScheduled,
		arg.ScheduledAt,
	)
	var i BroadcastJob
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.Name,
		&i.MessageType,
		&i.Content,
		&i.MediaUrl,
		&i.MediaFilename,
		&i.Cooldown,
		&i.Status,
		&i.IsScheduled,
		&i.ScheduledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createBroadcastRecipient = `-- name: CreateBroadcastRecipient :exec
INSERT INTO broadcast_recipients (job_id, recipient_jid)
VALUES ($1, $2)
ON CONFLICT (job_id, recipient_jid) DO NOTHING
`

type CreateBroadcastRecipientParams struct {
	JobID        pgtype.UUID `json:"job_id"`
	RecipientJid string      `json:"recipient_jid"`
}

func (q *Queries) CreateBroadcastRecipient(ctx context.Context, arg CreateBroadcastRecipientParams) error {
	_, err := q.db.Exec(ctx, createBroadcastRecipient, arg.JobID, arg.RecipientJid)
	return err
}

const getBroadcastJob = `-- name: GetBroadcastJob :one
SELECT id, user_id, device_id, name, message_type, content, media_url, media_filename, cooldown, status, is_scheduled, scheduled_at, created_at, updated_at FROM broadcast_jobs
WHERE id = $1 AND user_id = $2
`

type GetBroadcastJobParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.Int4 `json:"user_id"`
}

func (q *Queries) GetBroadcastJob(ctx context.Context, arg GetBroadcastJobParams) (BroadcastJob, error) {
	row := q.db.QueryRow(ctx, getBroadcastJob, arg.ID, arg.UserID)
	var i BroadcastJob
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.Name,
		&i.MessageType,
		&i.Content,
		&i.MediaUrl,
		&i.MediaFilename,
		&i.Cooldown,
		&i.Status,
		&i.IsScheduled,
		&i.ScheduledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBroadcastJobs = `-- name: GetBroadcastJobs :many
SELECT id, user_id, device_id, name, message_type, content, media_url, media_filename, cooldown, status, is_scheduled, scheduled_at, created_at, updated_at FROM broadcast_jobs
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetBroadcastJobs(ctx context.Context, userID pgtype.Int4) ([]BroadcastJob, error) {
	rows, err := q.db.Query(ctx, getBroadcastJobs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BroadcastJob
	for rows.Next() {
		var i BroadcastJob
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DeviceID,
			&i.Name,
			&i.MessageType,
			&i.Content,
			&i.MediaUrl,
			&i.MediaFilename,
			&i.Cooldown,
			&i.Status,
			&i.IsScheduled,
			&i.ScheduledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBroadcastRecipients = `-- name: GetBroadcastRecipients :many
SELECT id, job_id, recipient_jid, status, error_message, sent_at FROM broadcast_recipients
WHERE job_id = $1
`

func (q *Queries) GetBroadcastRecipients(ctx context.Context, jobID pgtype.UUID) ([]BroadcastRecipient, error) {
	rows, err := q.db.Query(ctx, getBroadcastRecipients, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BroadcastRecipient
	for rows.Next() {
		var i BroadcastRecipient
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.RecipientJid,
			&i.Status,
			&i.ErrorMessage,
			&i.SentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingBroadcastJobs = `-- name: GetPendingBroadcastJobs :many
SELECT id, user_id, device_id, name, message_type, content, media_url, media_filename, cooldown, status, is_scheduled, scheduled_at, created_at, updated_at FROM broadcast_jobs
WHERE status = 'pending' AND (is_scheduled = FALSE OR (is_scheduled = TRUE AND scheduled_at <= NOW()))
ORDER BY created_at ASC
`

func (q *Queries) GetPendingBroadcastJobs(ctx context.Context) ([]BroadcastJob, error) {
	rows, err := q.db.Query(ctx, getPendingBroadcastJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BroadcastJob
	for rows.Next() {
		var i BroadcastJob
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DeviceID,
			&i.Name,
			&i.MessageType,
			&i.Content,
			&i.MediaUrl,
			&i.MediaFilename,
			&i.Cooldown,
			&i.Status,
			&i.IsScheduled,
			&i.ScheduledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingRecipients = `-- name: GetPendingRecipients :many
SELECT id, job_id, recipient_jid, status, error_message, sent_at FROM broadcast_recipients
WHERE job_id = $1 AND status = 'pending'
ORDER BY id ASC
`

func (q *Queries) GetPendingRecipients(ctx context.Context, jobID pgtype.UUID) ([]BroadcastRecipient, error) {
	rows, err := q.db.Query(ctx, getPendingRecipients, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BroadcastRecipient
	for rows.Next() {
		var i BroadcastRecipient
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.RecipientJid,
			&i.Status,
			&i.ErrorMessage,
			&i.SentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBroadcastJobStatus = `-- name: UpdateBroadcastJobStatus :exec
UPDATE broadcast_jobs
SET status = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateBroadcastJobStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status pgtype.Text `json:"status"`
}

func (q *Queries) UpdateBroadcastJobStatus(ctx context.Context, arg UpdateBroadcastJobStatusParams) error {
	_, err := q.db.Exec(ctx, updateBroadcastJobStatus, arg.ID, arg.Status)
	return err
}

const updateBroadcastRecipientStatus = `-- name: UpdateBroadcastRecipientStatus :exec
UPDATE broadcast_recipients
SET status = $3, error_message = $4, sent_at = NOW()
WHERE job_id = $1 AND recipient_jid = $2
`

type UpdateBroadcastRecipientStatusParams struct {
	JobID        pgtype.UUID `json:"job_id"`
	RecipientJid string      `json:"recipient_jid"`
	Status       pgtype.Text `json:"status"`
	ErrorMessage pgtype.Text `json:"error_message"`
}

func (q *Queries) UpdateBroadcastRecipientStatus(ctx context.Context, arg UpdateBroadcastRecipientStatusParams) error {
	_, err := q.db.Exec(ctx, updateBroadcastRecipientStatus,
		arg.JobID,
		arg.RecipientJid,
		arg.Status,
		arg.ErrorMessage,
	)
	return err
}
