// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Client struct {
	ID             string             `json:"id"`
	Name           string             `json:"name"`
	WhatsappNumber pgtype.Text        `json:"whatsapp_number"`
	Jid            pgtype.Text        `json:"jid"`
	QrCode         pgtype.Text        `json:"qr_code"`
	IsConnected    pgtype.Bool        `json:"is_connected"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
	UserID         pgtype.Text        `json:"user_id"`
}

type User struct {
	ID           int32            `json:"id"`
	Username     string           `json:"username"`
	Password     string           `json:"password"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
	ApiKeyPrefix pgtype.Text      `json:"api_key_prefix"`
	ApiKey       pgtype.Text      `json:"api_key"`
}
