// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Client struct {
	ID             string             `json:"id"`
	Name           string             `json:"name"`
	WhatsappNumber pgtype.Text        `json:"whatsapp_number"`
	Jid            pgtype.Text        `json:"jid"`
	QrCode         pgtype.Text        `json:"qr_code"`
	IsConnected    pgtype.Bool        `json:"is_connected"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
	UserID         pgtype.Int4        `json:"user_id"`
}

type MessageLog struct {
	ID            pgtype.UUID        `json:"id"`
	DeviceID      pgtype.Text        `json:"device_id"`
	UserID        pgtype.Int4        `json:"user_id"`
	Recipient     string             `json:"recipient"`
	RecipientType pgtype.Text        `json:"recipient_type"`
	MessageType   pgtype.Text        `json:"message_type"`
	Content       string             `json:"content"`
	MediaUrl      pgtype.Text        `json:"media_url"`
	MediaFilename pgtype.Text        `json:"media_filename"`
	Buttons       []byte             `json:"buttons"`
	TemplateID    pgtype.UUID        `json:"template_id"`
	Status        pgtype.Text        `json:"status"`
	SentAt        pgtype.Timestamptz `json:"sent_at"`
	DeliveredAt   pgtype.Timestamptz `json:"delivered_at"`
	ReadAt        pgtype.Timestamptz `json:"read_at"`
	Direction     string             `json:"direction"`
	WaMessageID   pgtype.Text        `json:"wa_message_id"`
	SenderJid     pgtype.Text        `json:"sender_jid"`
}

type MessageTemplate struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.Int4        `json:"user_id"`
	Name      string             `json:"name"`
	Content   string             `json:"content"`
	Variables []byte             `json:"variables"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID           int32            `json:"id"`
	Email        string           `json:"email"`
	Password     string           `json:"password"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
	ApiKeyPrefix pgtype.Text      `json:"api_key_prefix"`
	ApiKey       pgtype.Text      `json:"api_key"`
}

type WhatsappContact struct {
	ID           pgtype.UUID        `json:"id"`
	DeviceID     pgtype.Text        `json:"device_id"`
	Jid          string             `json:"jid"`
	FullName     pgtype.Text        `json:"full_name"`
	PushName     pgtype.Text        `json:"push_name"`
	BusinessName pgtype.Text        `json:"business_name"`
	PhoneNumber  pgtype.Text        `json:"phone_number"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type WhatsappGroup struct {
	ID               pgtype.UUID        `json:"id"`
	DeviceID         pgtype.Text        `json:"device_id"`
	GroupID          string             `json:"group_id"`
	GroupName        string             `json:"group_name"`
	GroupDescription pgtype.Text        `json:"group_description"`
	ParticipantCount pgtype.Int4        `json:"participant_count"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}
