// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// filename: queries/clients/create_new_client.sql
	CreateNewClient(ctx context.Context, arg CreateNewClientParams) (Client, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteClient(ctx context.Context, id string) error
	DeleteUser(ctx context.Context, id int32) error
	GetClient(ctx context.Context, id string) (Client, error)
	GetClientByJID(ctx context.Context, jid pgtype.Text) (Client, error)
	GetClients(ctx context.Context) ([]Client, error)
	GetUserByAPIKey(ctx context.Context, apiKey pgtype.Text) (User, error)
	GetUserByID(ctx context.Context, id int32) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUsers(ctx context.Context) ([]User, error)
	RevokeUserAPIKey(ctx context.Context, id int32) error
	SetClientJID(ctx context.Context, arg SetClientJIDParams) (Client, error)
	SetConnectionStatus(ctx context.Context, arg SetConnectionStatusParams) (Client, error)
	SetUserAPIKey(ctx context.Context, arg SetUserAPIKeyParams) (User, error)
	SetUserAPIPrefix(ctx context.Context, arg SetUserAPIPrefixParams) error
	UpdateQRCode(ctx context.Context, arg UpdateQRCodeParams) (Client, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
