// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error)
	CreateBroadcastJob(ctx context.Context, arg CreateBroadcastJobParams) (BroadcastJob, error)
	CreateBroadcastRecipient(ctx context.Context, arg CreateBroadcastRecipientParams) error
	// filename: subscriptions.sql
	CreateDeviceSubscription(ctx context.Context, arg CreateDeviceSubscriptionParams) (DeviceSubscription, error)
	// filename: queries/clients/create_new_client.sql
	CreateNewClient(ctx context.Context, arg CreateNewClientParams) (Client, error)
	CreateNewMessageTemplate(ctx context.Context, arg CreateNewMessageTemplateParams) (MessageTemplate, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAPIKey(ctx context.Context, id pgtype.UUID) error
	DeleteAllDeviceSubscriptions(ctx context.Context, deviceID string) error
	DeleteClient(ctx context.Context, id string) error
	DeleteDeviceSubscription(ctx context.Context, arg DeleteDeviceSubscriptionParams) (DeviceSubscription, error)
	DeleteMessageTemplate(ctx context.Context, arg DeleteMessageTemplateParams) error
	DeleteUser(ctx context.Context, id int32) error
	GetAPIKeyByID(ctx context.Context, id pgtype.UUID) (ApiKey, error)
	GetAPIKeyByPrefix(ctx context.Context, keyPrefix string) (ApiKey, error)
	GetAPIKeyUsageLogs(ctx context.Context, arg GetAPIKeyUsageLogsParams) ([]ApiKeyLog, error)
	GetAPIKeysByUserID(ctx context.Context, userID int32) ([]ApiKey, error)
	GetAllDeviceSubscriptions(ctx context.Context) ([]DeviceSubscription, error)
	GetBroadcastJob(ctx context.Context, arg GetBroadcastJobParams) (BroadcastJob, error)
	GetBroadcastJobs(ctx context.Context, userID pgtype.Int4) ([]BroadcastJob, error)
	GetBroadcastRecipients(ctx context.Context, jobID pgtype.UUID) ([]BroadcastRecipient, error)
	GetClient(ctx context.Context, id string) (Client, error)
	GetClientByIDAndUserID(ctx context.Context, arg GetClientByIDAndUserIDParams) (Client, error)
	GetClientByJID(ctx context.Context, jid pgtype.Text) (Client, error)
	GetClients(ctx context.Context) ([]Client, error)
	GetClientsByUserID(ctx context.Context, userID pgtype.Int4) ([]Client, error)
	GetConversationMessages(ctx context.Context, arg GetConversationMessagesParams) ([]GetConversationMessagesRow, error)
	GetConversations(ctx context.Context, arg GetConversationsParams) ([]GetConversationsRow, error)
	GetDeviceContacts(ctx context.Context, deviceID pgtype.Text) ([]WhatsappContact, error)
	GetDeviceGroups(ctx context.Context, deviceID pgtype.Text) ([]WhatsappGroup, error)
	GetDeviceSubscription(ctx context.Context, arg GetDeviceSubscriptionParams) (DeviceSubscription, error)
	GetDeviceSubscriptions(ctx context.Context, deviceID string) ([]DeviceSubscription, error)
	GetMessageHistory(ctx context.Context, arg GetMessageHistoryParams) ([]MessageLog, error)
	GetMessageTemplateByID(ctx context.Context, id pgtype.UUID) (MessageTemplate, error)
	GetPendingBroadcastJobs(ctx context.Context) ([]BroadcastJob, error)
	GetPendingRecipients(ctx context.Context, jobID pgtype.UUID) ([]BroadcastRecipient, error)
	GetThreadMessages(ctx context.Context, arg GetThreadMessagesParams) ([]GetThreadMessagesRow, error)
	GetThreads(ctx context.Context, arg GetThreadsParams) ([]GetThreadsRow, error)
	GetUserByAPIKey(ctx context.Context, apiKey pgtype.Text) (User, error)
	GetUserByID(ctx context.Context, id int32) (User, error)
	GetUserByUsername(ctx context.Context, email string) (User, error)
	GetUserTemplates(ctx context.Context, userID pgtype.Int4) ([]MessageTemplate, error)
	GetUsers(ctx context.Context) ([]User, error)
	LogAPIKeyUsage(ctx context.Context, arg LogAPIKeyUsageParams) error
	LogIncomingMessage(ctx context.Context, arg LogIncomingMessageParams) (MessageLog, error)
	LogOutgoingMessage(ctx context.Context, arg LogOutgoingMessageParams) (MessageLog, error)
	MarkConversationRead(ctx context.Context, arg MarkConversationReadParams) error
	ResetThreadUnread(ctx context.Context, arg ResetThreadUnreadParams) error
	RevokeUserAPIKey(ctx context.Context, id int32) error
	SendMessageData(ctx context.Context, arg SendMessageDataParams) (MessageLog, error)
	SetClientJID(ctx context.Context, arg SetClientJIDParams) (Client, error)
	SetConnectionStatus(ctx context.Context, arg SetConnectionStatusParams) (Client, error)
	SetUserAPIKey(ctx context.Context, arg SetUserAPIKeyParams) (User, error)
	SetUserAPIPrefix(ctx context.Context, arg SetUserAPIPrefixParams) error
	UpdateAPIKeyLastUsed(ctx context.Context, id pgtype.UUID) error
	UpdateBroadcastJobStatus(ctx context.Context, arg UpdateBroadcastJobStatusParams) error
	UpdateBroadcastRecipientStatus(ctx context.Context, arg UpdateBroadcastRecipientStatusParams) error
	UpdateDeviceSubscription(ctx context.Context, arg UpdateDeviceSubscriptionParams) (DeviceSubscription, error)
	UpdateMessageStatus(ctx context.Context, arg UpdateMessageStatusParams) error
	UpdateMessageTemplate(ctx context.Context, arg UpdateMessageTemplateParams) (MessageTemplate, error)
	UpdateQRCode(ctx context.Context, arg UpdateQRCodeParams) (Client, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error)
	UpsertDeviceSubscriptions(ctx context.Context, arg UpsertDeviceSubscriptionsParams) error
	UpsertThread(ctx context.Context, arg UpsertThreadParams) error
	UpsertWhatsAppContact(ctx context.Context, arg UpsertWhatsAppContactParams) error
	UpsertWhatsAppGroup(ctx context.Context, arg UpsertWhatsAppGroupParams) error
}

var _ Querier = (*Queries)(nil)
