// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// filename: queries/clients/create_new_client.sql
	CreateNewClient(ctx context.Context, arg CreateNewClientParams) (Client, error)
	CreateNewMessageTemplate(ctx context.Context, arg CreateNewMessageTemplateParams) (MessageTemplate, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteClient(ctx context.Context, id string) error
	DeleteMessageTemplate(ctx context.Context, arg DeleteMessageTemplateParams) error
	DeleteUser(ctx context.Context, id int32) error
	GetClient(ctx context.Context, id string) (Client, error)
	GetClientByJID(ctx context.Context, jid pgtype.Text) (Client, error)
	GetClients(ctx context.Context) ([]Client, error)
	GetConversationMessages(ctx context.Context, arg GetConversationMessagesParams) ([]GetConversationMessagesRow, error)
	GetConversations(ctx context.Context, arg GetConversationsParams) ([]GetConversationsRow, error)
	GetDeviceContacts(ctx context.Context, deviceID pgtype.Text) ([]WhatsappContact, error)
	GetDeviceGroups(ctx context.Context, deviceID pgtype.Text) ([]WhatsappGroup, error)
	GetMessageHistory(ctx context.Context, arg GetMessageHistoryParams) ([]MessageLog, error)
	GetMessageTemplateByID(ctx context.Context, id pgtype.UUID) (MessageTemplate, error)
	GetThreadMessages(ctx context.Context, arg GetThreadMessagesParams) ([]GetThreadMessagesRow, error)
	GetThreads(ctx context.Context, arg GetThreadsParams) ([]GetThreadsRow, error)
	GetUserByAPIKey(ctx context.Context, apiKey pgtype.Text) (User, error)
	GetUserByID(ctx context.Context, id int32) (User, error)
	GetUserByUsername(ctx context.Context, email string) (User, error)
	GetUserTemplates(ctx context.Context, userID pgtype.Int4) ([]MessageTemplate, error)
	GetUsers(ctx context.Context) ([]User, error)
	LogIncomingMessage(ctx context.Context, arg LogIncomingMessageParams) (MessageLog, error)
	LogOutgoingMessage(ctx context.Context, arg LogOutgoingMessageParams) (MessageLog, error)
	MarkConversationRead(ctx context.Context, arg MarkConversationReadParams) error
	ResetThreadUnread(ctx context.Context, arg ResetThreadUnreadParams) error
	RevokeUserAPIKey(ctx context.Context, id int32) error
	SendMessageData(ctx context.Context, arg SendMessageDataParams) (MessageLog, error)
	SetClientJID(ctx context.Context, arg SetClientJIDParams) (Client, error)
	SetConnectionStatus(ctx context.Context, arg SetConnectionStatusParams) (Client, error)
	SetUserAPIKey(ctx context.Context, arg SetUserAPIKeyParams) (User, error)
	SetUserAPIPrefix(ctx context.Context, arg SetUserAPIPrefixParams) error
	UpdateMessageStatus(ctx context.Context, arg UpdateMessageStatusParams) error
	UpdateMessageTemplate(ctx context.Context, arg UpdateMessageTemplateParams) (MessageTemplate, error)
	UpdateQRCode(ctx context.Context, arg UpdateQRCodeParams) (Client, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpsertThread(ctx context.Context, arg UpsertThreadParams) error
	UpsertWhatsAppContact(ctx context.Context, arg UpsertWhatsAppContactParams) error
	UpsertWhatsAppGroup(ctx context.Context, arg UpsertWhatsAppGroupParams) error
}

var _ Querier = (*Queries)(nil)
