// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subscriptions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDeviceSubscription = `-- name: CreateDeviceSubscription :one

INSERT INTO device_subscriptions (device_id, event_type, enabled)
VALUES ($1, $2, $3)
ON CONFLICT (device_id, event_type) 
DO UPDATE SET enabled = EXCLUDED.enabled
RETURNING id, device_id, event_type, enabled, created_at, updated_at
`

type CreateDeviceSubscriptionParams struct {
	DeviceID  string      `json:"device_id"`
	EventType string      `json:"event_type"`
	Enabled   pgtype.Bool `json:"enabled"`
}

// filename: subscriptions.sql
func (q *Queries) CreateDeviceSubscription(ctx context.Context, arg CreateDeviceSubscriptionParams) (DeviceSubscription, error) {
	row := q.db.QueryRow(ctx, createDeviceSubscription, arg.DeviceID, arg.EventType, arg.Enabled)
	var i DeviceSubscription
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.EventType,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAllDeviceSubscriptions = `-- name: DeleteAllDeviceSubscriptions :exec
DELETE FROM device_subscriptions
WHERE device_id = $1
`

func (q *Queries) DeleteAllDeviceSubscriptions(ctx context.Context, deviceID string) error {
	_, err := q.db.Exec(ctx, deleteAllDeviceSubscriptions, deviceID)
	return err
}

const deleteDeviceSubscription = `-- name: DeleteDeviceSubscription :one
DELETE FROM device_subscriptions
WHERE device_id = $1 AND event_type = $2
RETURNING id, device_id, event_type, enabled, created_at, updated_at
`

type DeleteDeviceSubscriptionParams struct {
	DeviceID  string `json:"device_id"`
	EventType string `json:"event_type"`
}

func (q *Queries) DeleteDeviceSubscription(ctx context.Context, arg DeleteDeviceSubscriptionParams) (DeviceSubscription, error) {
	row := q.db.QueryRow(ctx, deleteDeviceSubscription, arg.DeviceID, arg.EventType)
	var i DeviceSubscription
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.EventType,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAllDeviceSubscriptions = `-- name: GetAllDeviceSubscriptions :many
SELECT id, device_id, event_type, enabled, created_at, updated_at
FROM device_subscriptions
`

func (q *Queries) GetAllDeviceSubscriptions(ctx context.Context) ([]DeviceSubscription, error) {
	rows, err := q.db.Query(ctx, getAllDeviceSubscriptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeviceSubscription
	for rows.Next() {
		var i DeviceSubscription
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.EventType,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDeviceSubscription = `-- name: GetDeviceSubscription :one
SELECT id, device_id, event_type, enabled, created_at, updated_at
FROM device_subscriptions
WHERE device_id = $1 AND event_type = $2
LIMIT 1
`

type GetDeviceSubscriptionParams struct {
	DeviceID  string `json:"device_id"`
	EventType string `json:"event_type"`
}

func (q *Queries) GetDeviceSubscription(ctx context.Context, arg GetDeviceSubscriptionParams) (DeviceSubscription, error) {
	row := q.db.QueryRow(ctx, getDeviceSubscription, arg.DeviceID, arg.EventType)
	var i DeviceSubscription
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.EventType,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeviceSubscriptions = `-- name: GetDeviceSubscriptions :many
SELECT id, device_id, event_type, enabled, created_at, updated_at
FROM device_subscriptions
WHERE device_id = $1
`

func (q *Queries) GetDeviceSubscriptions(ctx context.Context, deviceID string) ([]DeviceSubscription, error) {
	rows, err := q.db.Query(ctx, getDeviceSubscriptions, deviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeviceSubscription
	for rows.Next() {
		var i DeviceSubscription
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.EventType,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDeviceSubscription = `-- name: UpdateDeviceSubscription :one
UPDATE device_subscriptions
SET enabled = $1
WHERE device_id = $2 AND event_type = $3
RETURNING id, device_id, event_type, enabled, created_at, updated_at
`

type UpdateDeviceSubscriptionParams struct {
	Enabled   pgtype.Bool `json:"enabled"`
	DeviceID  string      `json:"device_id"`
	EventType string      `json:"event_type"`
}

func (q *Queries) UpdateDeviceSubscription(ctx context.Context, arg UpdateDeviceSubscriptionParams) (DeviceSubscription, error) {
	row := q.db.QueryRow(ctx, updateDeviceSubscription, arg.Enabled, arg.DeviceID, arg.EventType)
	var i DeviceSubscription
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.EventType,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertDeviceSubscriptions = `-- name: UpsertDeviceSubscriptions :exec
INSERT INTO device_subscriptions (device_id, event_type, enabled)
VALUES ($1, $2, $3)
ON CONFLICT (device_id, event_type) 
DO UPDATE SET enabled = EXCLUDED.enabled
`

type UpsertDeviceSubscriptionsParams struct {
	DeviceID  string      `json:"device_id"`
	EventType string      `json:"event_type"`
	Enabled   pgtype.Bool `json:"enabled"`
}

func (q *Queries) UpsertDeviceSubscriptions(ctx context.Context, arg UpsertDeviceSubscriptionsParams) error {
	_, err := q.db.Exec(ctx, upsertDeviceSubscriptions, arg.DeviceID, arg.EventType, arg.Enabled)
	return err
}
