// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: whatsapp_contacts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDeviceContacts = `-- name: GetDeviceContacts :many
SELECT id, device_id, jid, full_name, push_name, business_name, phone_number, created_at, updated_at
FROM whatsapp_contacts
WHERE device_id = $1
ORDER BY COALESCE(full_name, push_name, jid) ASC
`

func (q *Queries) GetDeviceContacts(ctx context.Context, deviceID pgtype.Text) ([]WhatsappContact, error) {
	rows, err := q.db.Query(ctx, getDeviceContacts, deviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WhatsappContact
	for rows.Next() {
		var i WhatsappContact
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.Jid,
			&i.FullName,
			&i.PushName,
			&i.BusinessName,
			&i.PhoneNumber,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertWhatsAppContact = `-- name: UpsertWhatsAppContact :exec
INSERT INTO whatsapp_contacts (device_id,
                               jid,
                               full_name,
                               push_name,
                               business_name,
                               phone_number,
                               updated_at)
VALUES ($1, $2, $3, $4, $5, $6, NOW())
ON CONFLICT (device_id, jid)
    DO UPDATE SET full_name     = EXCLUDED.full_name,
                  push_name     = EXCLUDED.push_name,
                  business_name = EXCLUDED.business_name,
                  phone_number  = EXCLUDED.phone_number,
                  updated_at    = EXCLUDED.updated_at
`

type UpsertWhatsAppContactParams struct {
	DeviceID     pgtype.Text `json:"device_id"`
	Jid          string      `json:"jid"`
	FullName     pgtype.Text `json:"full_name"`
	PushName     pgtype.Text `json:"push_name"`
	BusinessName pgtype.Text `json:"business_name"`
	PhoneNumber  pgtype.Text `json:"phone_number"`
}

func (q *Queries) UpsertWhatsAppContact(ctx context.Context, arg UpsertWhatsAppContactParams) error {
	_, err := q.db.Exec(ctx, upsertWhatsAppContact,
		arg.DeviceID,
		arg.Jid,
		arg.FullName,
		arg.PushName,
		arg.BusinessName,
		arg.PhoneNumber,
	)
	return err
}
