version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=8080
      - HOST=0.0.0.0
      - DB=postgres://user:password@db:5432/dbname
      - JWT_SECRET=your_jwt_secret
      - INIT_USER=admin
      - INIT_PASS=password
    ports:
      - "8080:8080"
    depends_on:
      - db
      - migrate

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - BACKEND_URL=http://api:8080/v1
      - AUTH_SECRET=your_auth_secret
      - NEXT_PUBLIC_API_URL=http://localhost:3000/api
      - TZ=Asia/Jakarta
    ports:
      - "3000:3000"
    depends_on:
      - api

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dbname
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  migrate:
    image: migrate/migrate
    command: [
      "-path", "/migrations",
      "-database", "postgres://user:password@db:5432/dbname?sslmode=disable",
      "up"
    ]
    volumes:
      - ./sql:/migrations
    depends_on:
      - db

volumes:
  db_data: